# -*- coding: utf-8 -*-
"""将 docs/TEST_PLAN.md 整理为 Excel 测试用例表。"""
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

# 每条: (编号, 章节/模块, 用例名称, 优先级, 前置条件, 测试步骤, 预期结果)
ROWS = [
    # ===== 3 功能测试 P1 =====
    ("TC-FN-OV-01", "3 功能-System Overview", "压力总览三表显示", "P1",
     "后端运行，系统空闲。",
     "1. 浏览器打开 UI，进入 System Overview。\n2. 观察 Disk IO / System / Network 三个压力表盘。\n3. 用 fio 制造磁盘压力，观察 Disk IO 表盘变化。",
     "三表显示 0–100% 数值与 LOW/MEDIUM/HIGH/CRITICAL 等级；颜色与等级一致；施压后 Disk IO 表读数与等级随之上升。"),
    ("TC-FN-OV-02", "3 功能-System Overview", "资源卡片渲染", "P1",
     "后端运行。",
     "进入 System Overview，逐一检查 CPU、Memory、Disk、Network、NPU、iGPU 六张卡片。",
     "数值、单位、趋势曲线均正确渲染；无 NaN/undefined/空白。"),
    ("TC-FN-OV-03", "3 功能-System Overview", "刷新间隔切换", "P1",
     "打开浏览器开发者工具 Network 面板。",
     "分别选择刷新间隔 2s / 3s / 5s，观察 /monitor/dynamic_info 请求间隔。",
     "请求间隔与所选值一致。"),
    ("TC-FN-OV-04", "3 功能-System Overview", "时间窗切换", "P1",
     "",
     "切换 Trend / Last 1 min / Last 5 min。",
     "曲线横轴时间窗随之变化，数据不错位。"),
    ("TC-FN-OV-05", "3 功能-System Overview", "关闭 Refresh", "P1",
     "",
     "关闭 Refresh 开关，观察 Network 面板与页面数据。",
     "停止发起轮询请求，页面数据冻结在最后一帧。"),
    ("TC-FN-AR-01", "3 功能-App Resources", "Top-N 应用资源榜", "P1",
     "运行 2–3 个已知资源占用的进程。",
     "进入 App Resources，对照 curl -k \"https://localhost:9001/monitor/app_resource_stats?n=10\"。",
     "UI 列表与接口返回一致；按 score 降序排列。"),
    ("TC-FN-AR-02", "3 功能-App Resources", "调整排名权重后排序变化", "P1",
     "记录当前榜单顺序。",
     "在设置中把 GPU 权重调高（或经 /monitor/config/weights_top），刷新榜单。",
     "GPU 占用高的应用排名上升；磁盘 I/O 榜仍按纯吞吐排序（I/O 权重不可配）。"),
    ("TC-FN-PR-01", "3 功能-Processes", "进程列表", "P1",
     "",
     "进入 Processes，对照 top -b -n1。",
     "按 CPU 降序；PID/名称/用户/CPU%/内存 字段完整；数量级与 top 一致。"),
    ("TC-FN-PR-02", "3 功能-Processes", "大量进程渲染", "P1",
     "系统进程数 > 1000（可用脚本批量拉起 sleep）。",
     "打开 Processes 页，滚动列表。",
     "渲染无卡顿、无截断错误、无崩溃。"),
    ("TC-FN-HS-01", "3 功能-History", "历史时间范围筛选", "P1",
     "服务已运行并积累历史快照。",
     "在 History 选择不同时间范围；对照 curl -k \"https://localhost:9001/monitor/history?range_seconds=300\"。",
     "曲线数据点落在所选范围内，与接口 count 一致。"),
    ("TC-FN-HS-03", "3 功能-History", "空历史友好提示", "P1",
     "全新启动、无历史数据。",
     "打开 History。",
     "显示空态提示，不报错、不白屏。"),
    ("TC-FN-BL-01", "3 功能-Balancer", "受控应用列表加载", "P1",
     "",
     "进入 Balancer，对照 curl -k -X POST https://localhost:9001/app/get_controlled_app -d '{}'。",
     "展示每个 app 的优先级、OOM 分值、状态，与接口一致。"),
    ("TC-FN-BL-02", "3 功能-Balancer", "AddApp 向导全链路", "P1",
     "存在一个可被关键词匹配的运行进程。",
     "1. 点击 Add App，输入关键词 → 触发 discover_search。\n2. 勾选候选进程 → 触发 discover_extract，检查自动填充的 bpf_name/process_names/commandline/id。\n3. 填写名称、优先级 → 提交 new_controlled_app。",
     "三步顺畅；字段自动填充正确；提交后 app 出现在受控列表，且 config.yaml 的 controlled_apps 已追加该条目。"),
    ("TC-FN-BL-04", "3 功能-Balancer", "资源限额编辑（受上下界约束）", "P1",
     "选定一个受控 app。",
     "1. 打开限额编辑，先取 resource_limit_profile（默认值 + min/max）。\n2. 输入合法值提交 → resource_limit。\n3. 尝试输入超上界/负值提交。",
     "合法值成功；非法值被前端拦截或后端返回 101/102；表单滑块受 min/max 约束。"),
    ("TC-FN-BL-05", "3 功能-Balancer", "恢复/软移除/硬删除", "P1",
     "",
     "对同一 app 依次执行 restore、remove_from_control、purge_controlled_app。",
     "restore 后限额清除；remove 仅 controlled=false，仍在 config 可再启用；purge 后 config + DB + BPF 三处均删除干净。"),
    ("TC-FN-BL-07", "3 功能-Balancer", "passive_control 开关", "P1",
     "制造系统高压力使自动限额本会触发。",
     "1. 关闭 passive_control（/monitor/config/passive_control enabled=false）。\n2. 施加 CPU 压力至 high。\n3. 观察是否对 top app 自动限额。\n4. 手动下发一次限额、并保持网络控制开启。",
     "关闭后不再自动限额/恢复；但手动限额与网络控制仍生效。"),
    ("TC-FN-AB-01", "3 功能-About", "About 静态信息", "P1",
     "",
     "进入 About，对照 dmidecode、uname -a、lscpu、free -h。",
     "BIOS/OS/内核/CPU/内存/GPU/NPU/驱动/固件 与系统实际一致。"),
    ("TC-FN-ERR-01", "3 功能-错误处理", "后端断连", "P1",
     "",
     "UI 打开状态下 systemctl stop（或 kill）后端；观察 UI；再启动后端。",
     "UI 显示明确错误态（非白屏）；后端恢复后自动重连、数据恢复刷新。"),
    ("TC-FN-ERR-02", "3 功能-错误处理", "SSE 断开重连", "P1",
     "",
     "断开网络/重启后端，观察 /app/events 连接。",
     "SSE 自动重连；不重复堆积历史事件。"),
    ("TC-FN-ERR-03", "3 功能-错误处理", "非法限额提交", "P1",
     "",
     "resource_limit 提交负数 / 超上界 / 非数字。",
     "返回 101 ARGUMENT_ERROR 或 102 DATA_ERROR；后端不写入坏值到 cgroup。"),
    ("TC-FN-ERR-04", "3 功能-错误处理", "AddApp 冲突", "P1",
     "",
     "new_controlled_app 提交已存在的 id / name / 进程重叠项。",
     "返回 409 CONFLICT，data.conflict 指明冲突类型，提示可 purge 后重加。"),
    ("TC-FN-ERR-05", "3 功能-错误处理", "对不存在 app 操作", "P1",
     "",
     "对不存在的 app_id 执行 limit / restore / cancel_relaunch。",
     "返回 404 NOT_EXISTING 或 103 OPERATING_ERROR，不崩溃。"),
    ("TC-FN-ERR-07", "3 功能-错误处理", "缺失数据源展示", "P1",
     "无 NPU 或无 iGPU 的平台。",
     "查看 System Overview 对应卡片。",
     "明确标注\"不支持/不可用\"，而非显示误导性的 0.0%。"),

    # ===== 4 调控正确性 P0 =====
    ("TC-CT-CPU-01", "4 调控正确性", "按优先级下发 CPU 限额并核对 cpu.max", "P0",
     "受控 app app_id=X，其 cgroup/scope 已知（记 $SCOPE）；策略 high=0.7。",
     "1. 设优先级 high：curl -k -X POST .../app/set_priority -d '{\"app_id\":\"X\",\"priority\":80}'\n2. 下发限额：curl -k -X POST .../app/resource_limit -d '{\"app_id\":\"X\",\"app_name\":\"...\",\"priority\":\"high\"}'\n3. 读取：cat /sys/fs/cgroup/$SCOPE/cpu.max",
     "cpu.max 的 quota/period ≈ 0.7 × 核数（按实现的周期基准换算），与策略一致。"),
    ("TC-CT-CPU-02", "4 调控正确性", "CPU 限额实测生效", "P0",
     "接 TC-CT-CPU-01。",
     "1. 在该 app 内跑 stress-ng --cpu <N> --timeout 60s。\n2. 用 top -p <pids> / mpstat 观察实际占用。",
     "实际 CPU 占用被压到配额附近（±容差），不超配额。"),
    ("TC-CT-CPU-04", "4 调控正确性", "CPU 限额恢复", "P0",
     "",
     "curl -k -X POST .../app/resource_restore -d '{\"app_id\":\"X\"}'；再 cat cpu.max。",
     "cpu.max 恢复为 max；重新压测占用可回升。"),
    ("TC-CT-CPU-05", "4 调控正确性", "critical 应用不被限", "P0",
     "",
     "设 app 为 critical，触发限额流程，读 cpu.max。",
     "critical 无 CPU 限额比例（策略未配），cpu.max 保持 max。"),
    ("TC-CT-MEM-01", "4 调控正确性", "memory.high 按比例", "P0",
     "app 优先级 high（策略 mem high=0.3）。",
     "下发限额后 cat /sys/fs/cgroup/$SCOPE/memory.high。",
     "值 ≈ 0.3 × 系统内存（按实现基准）。"),
    ("TC-CT-MEM-02", "4 调控正确性", "内存回收实测", "P0",
     "",
     "app 内 stress-ng --vm 1 --vm-bytes <大于 high>，观察是否触发回收（memory.high 事件 / RSS 被压制）。",
     "内存增长在接近 high 阈值时被抑制。"),
    ("TC-CT-IO-01", "4 调控正确性", "io.max 下发核对", "P0",
     "app 优先级 low（write=20MB/s、read=30MB/s、write_iops=1200、read_iops=11000）。",
     "下发限额后 cat /sys/fs/cgroup/$SCOPE/io.max，确认对应盘的 major:minor。",
     "rbps/wbps/riops/wiops 与 low 策略换算值一致。"),
    ("TC-CT-IO-02", "4 调控正确性", "磁盘限速实测", "P0",
     "",
     "app 内 fio --rw=write --bs=1M --size=2G --name=t，用 iostat -x 1 观察吞吐。",
     "实测写吞吐 ≈ 20 MB/s（±容差）。"),
    ("TC-CT-IO-04", "4 调控正确性", "I/O 渐进恢复", "P0",
     "",
     "撤除磁盘压力后持续观察 io.max。",
     "压力回落后限额逐步放开直至移除。"),
    ("TC-CT-NET-01", "4 调控正确性", "网络规则下发", "P0",
     "enable_network_control=true，network_interface 正确。",
     "启用后 tc qdisc show dev <iface>、tc class show dev <iface>、iptables -t mangle -L。",
     "存在 HTB qdisc/class 与四优先级（system/critical/high/low）分类及 mark 规则。"),
    ("TC-CT-NET-02", "4 调控正确性", "出向限速实测", "P0",
     "内置 testing_network_app: iperf（critical，session-1879.scope）。",
     "iperf3 -c <server> 发流，观察带宽。",
     "实测带宽落在该优先级配置区间（critical 500000–900000 kbit/s）。"),
    ("TC-CT-NET-04", "4 调控正确性", "系统端口豁免", "P0",
     "",
     "对端口 22/53/80/443/123 产生流量，观察是否被限。",
     "系统端口流量不受带宽限制。"),
    ("TC-CT-NET-05", "4 调控正确性", "网络压力升至 critical 收紧", "P0",
     "",
     "持续打满带宽使 network pressure 达 critical。",
     "依次收紧 low、high 类带宽上限；tc class 的 ceil 值下降。"),
    ("TC-CT-NET-06", "4 调控正确性", "网络规则清除", "P0",
     "",
     "停止网络控制 / 停服务后 tc qdisc show、iptables -t mangle -L。",
     "HTB、IFB、iptables mark 规则完全清除，无残留导致网络异常。"),
    ("TC-CT-GOV-01/02", "4 调控正确性", "Governor 切换", "P0",
     "",
     "施压使分级达 high → cpupower frequency-info；撤压回 low → 再查。",
     "高压切 performance（频率上升），低压回 powersave。"),
    ("TC-CT-GOV-03", "4 调控正确性", "无 cpupower 降级", "P0",
     "卸载/屏蔽 cpupower。",
     "触发 governor 切换。",
     "优雅失败并告警，不崩溃、不卡系统。"),
    ("TC-CT-OOM-01", "4 调控正确性", "OOM 保护值", "P0",
     "",
     "对 critical app 设 OOM 保护 → cat /proc/<pid>/oom_score_adj。",
     "值为 -500（或配置值）。"),
    ("TC-CT-OOM-03", "4 调控正确性", "OOM 恢复", "P0",
     "",
     "remove_from_control 后再读 oom_score_adj。",
     "恢复为原始值。"),
    ("TC-CT-LOOP-01", "4 调控正确性", "压力驱动自动限额（闭环上行）", "P0",
     "passive_control=true，存在受控 top app。",
     "stress-ng 施加 CPU/内存/IO 压力，使 PSI 分级升至 high/critical。",
     "balancer 自动对 top app 施加限额（cgroup 值变化）并切 governor 为 performance。"),
    ("TC-CT-LOOP-02", "4 调控正确性", "cooldown 防抖", "P0",
     "",
     "在压力临界值附近波动，观察限额调整频率。",
     "遵守 cooldown_time（默认 15s），不频繁抖动。"),
    ("TC-CT-LOOP-03", "4 调控正确性", "压力回落渐进恢复（闭环下行）", "P0",
     "",
     "停止施压，持续观察 cgroup 值与 governor。",
     "配额逐步恢复至无限制，governor 回 powersave。"),
    ("TC-CT-PQ-01/02/03", "4 调控正确性", "优先级队列", "P0",
     "制造 critical 压力或磁盘忙。",
     "1. 启动多个不同优先级的受控 app。\n2. 查询 /app/get_pending_app。\n3. 撤除压力，观察自动拉起顺序。\n4. 对某待启动项调用 cancel_relaunch。",
     "压力期入队不拉起；恢复后按优先级 DESC 依次拉起；取消项状态变 stopped 并从队列移除。"),
    ("TC-CT-BPF-01/02", "4 调控正确性", "eBPF 启动/退出检测", "P0",
     "BCC 可用；已注册含 bpf_name 的受控 app。",
     "启动该 app（execve）→ 观察 SSE；再退出该 app → 观察 SSE。",
     "启动被实时检测并纳管、SSE 推 running；退出被检测、SSE 推状态、限额被清理。"),
    ("TC-CT-BPF-04", "4 调控正确性", "多进程/多 cgroup 聚合", "P0",
     "process_names 含多个进程、分布在多 cgroup。",
     "查看该 app 的资源统计。",
     "跨 cgroup 资源正确聚合，无遗漏、无重复计。"),

    # ===== 5 安全与破坏性/恢复 P0 =====
    ("TC-SF-01", "5 安全与恢复", "后端 kill 后残留", "P0",
     "已对某 app 施加限额。",
     "kill -9 <backend_pid>；检查 /sys/fs/cgroup/$SCOPE/cpu.max 等；重启后端。",
     "重启后能识别/接管或清理，无孤儿 cgroup 累积。"),
    ("TC-SF-02", "5 安全与恢复", "网络控制中崩溃残留", "P0",
     "",
     "启用网络控制后 kill 后端；tc qdisc show、iptables -t mangle -L；重启。",
     "规则被清理或重启后重建；不残留导致断网。"),
    ("TC-SF-03", "5 安全与恢复", "正常重启后接管", "P0",
     "",
     "systemctl restart 后端 → /app/check_running_apps。",
     "已有受控 app 被重新识别，状态一致。"),
    ("TC-SF-04", "5 安全与恢复", "停服务/卸载清理", "P0",
     "",
     "停服务后全面检查 cgroup 限额、tc、iptables、oom_score_adj、governor。",
     "全部恢复默认，系统干净无残留。"),
    ("TC-SF-05", "5 安全与恢复", "黑名单强约束（S1 重点）", "P0",
     "blacklist 含 kworker/systemd/dbus/pipewire 等。",
     "1. 尝试通过向导 discover_search 搜索这些进程名。\n2. 尝试对其纳管/限额。\n3. 施加系统高压力，观察 balancer 是否会限制系统进程。",
     "黑名单进程绝不出现在候选、绝不被纳管或限制。"),
    ("TC-SF-06", "5 安全与恢复", "极端限额的下界保护", "P0",
     "",
     "尝试下发极小 CPU 配额（趋近 0）。",
     "有下界保护，cpu.max 不为 0；系统不卡死。"),
    ("TC-SF-07", "5 安全与恢复", "配置网卡不存在", "P0",
     "network_interface 改为不存在的名字，重启。",
     "启用网络控制。",
     "安全跳过并告警，不影响其它功能。"),
    ("TC-SF-09", "5 安全与恢复", "限额/恢复反复压力（泄漏）", "P0",
     "",
     "脚本循环 limit→restore 1000 次；期间监控 cgroup 数量、后端句柄/内存。",
     "无 cgroup/规则泄漏，无句柄/内存泄漏。"),

    # ===== 6 监控数据准确性 P0 =====
    ("TC-AC-01", "6 监控准确性", "CPU 总/分核、P/E/LPE", "P0",
     "施加可控 CPU 负载。",
     "同时取 dynamic_info.cpu 与 mpstat -P ALL 1。",
     "数量级与趋势一致，误差 ≤ 约定容差。"),
    ("TC-AC-02", "6 监控准确性", "内存/swap", "P0",
     "跑内存负载。",
     "对照 free -m、/proc/meminfo。",
     "一致。"),
    ("TC-AC-03", "6 监控准确性", "磁盘吞吐/IOPS/iowait/util", "P0",
     "fio 施压。",
     "对照 iostat -x 1。",
     "一致。"),
    ("TC-AC-04", "6 监控准确性", "网络 tx/rx", "P0",
     "iperf3 发流。",
     "对照 /sys/class/net/*/statistics、ifstat。",
     "一致。"),
    ("TC-AC-05", "6 监控准确性", "iGPU 引擎/频率/功耗/VRAM", "P0",
     "GPU 负载。",
     "对照 intel_gpu_top/xpu-smi。",
     "一致。"),
    ("TC-AC-06", "6 监控准确性", "NPU 利用率/功耗/温度/频率", "P0",
     "NPU 负载。",
     "对照 PMT/xpu-smi（MTL/ARL/LNL/PTL）。",
     "一致。"),
    ("TC-AC-07", "6 监控准确性", "每应用 CPU/内存/GPU/NPU 显存", "P0",
     "已知负载进程。",
     "核对 app_resource_stats 归属。",
     "归属正确、无串号。"),
    ("TC-AC-08", "6 监控准确性", "PSI 分数与四级分级", "P0",
     "逐级施压。",
     "按 thresholds(0.4/0.6/0.8/1.0)+weights(cpu2/mem7/io1) 手算复核。",
     "分级边界正确。"),
    ("TC-AC-09", "6 监控准确性", "排名 score", "P0",
     "多负载进程。",
     "按 weights_top(cpu2/mem7/gpu5) 复算。",
     "排序与分值正确。"),
    ("TC-AC-10", "6 监控准确性", "空闲态", "P0",
     "系统空闲。",
     "观察各指标。",
     "接近 0，无异常尖峰。"),

    # ===== 7 后端 API 系统测试 P1 =====
    ("TC-API-AUTH-01", "7 API 系统测试", "登录", "P1",
     "",
     "curl -k -X POST https://localhost:9001/auth/login -H 'Content-Type: application/json' -d '{\"pwd\":\"<正确token>\"}'",
     "retcode=0，data.authenticated=true。"),
    ("TC-API-AUTH-02", "7 API 系统测试", "错误 token", "P1",
     "",
     "同上传入错误 token。",
     "data.authenticated=false；响应不泄露\"用户存在性\"等信息。"),
    ("TC-API-AUTH-03", "7 API 系统测试", "未鉴权访问", "P1",
     "",
     "未登录直接调用受保护端点。",
     "返回 401 UNAUTHORIZED / 109。"),
    ("TC-API-APP-01", "7 API 系统测试", "App 端点 happy path（批量）", "P1",
     "准备一个受控 app。",
     "依次调用 get_apps、set_priority、get_priority_data、set_to_control、get_controlled_app、get_pending_app、set_oom_score、resource_limit_profile、resource_limit、resource_restore、remove_from_control、purge_controlled_app，逐个检查返回。",
     "全部 retcode=0；data 结构符合 docs/API_ENDPOINTS.md 契约。"),
    ("TC-API-APP-02", "7 API 系统测试", "缺必填参数", "P1",
     "",
     "set_priority 缺 app_id 或 priority；resource_limit 缺 priority。",
     "返回 101 ARGUMENT_ERROR。"),
    ("TC-API-APP-03", "7 API 系统测试", "get_priority_data 参数组合", "P1",
     "",
     "分别仅传 app_name、仅传 app_id、都不传。",
     "前两成功；都不传返回参数错误。"),
    ("TC-API-APP-04", "7 API 系统测试", "new_controlled_app 冲突", "P1",
     "",
     "提交重复 id / name / 进程重叠。",
     "409，data.conflict 指明 id/name/进程重叠。"),
    ("TC-API-APP-06", "7 API 系统测试", "discover_extract 非法 pid", "P1",
     "",
     "传入不存在的 pid、系统关键 pid、负数。",
     "优雅处理，不崩溃，不越权。"),
    ("TC-API-APP-08", "7 API 系统测试", "SSE 契约", "P1",
     "",
     "curl -k -N https://localhost:9001/app/events，保持连接 ≥ 60s；期间触发一次 app 状态变化。",
     "首帧 {\"type\":\"connected\"}；空闲每 30s 有 : heartbeat；状态变化推送含 app_id/app_name/status/purpose。"),
    ("TC-API-MON-01", "7 API 系统测试", "app_resource_stats n 边界", "P1",
     "",
     "?n=0、?n=-1、?n=100000、?n=abc。",
     "合理裁剪/默认值，不崩溃。"),
    ("TC-API-MON-02", "7 API 系统测试", "history 参数组合", "P1",
     "",
     "组合 snapshot_type(static/dynamic/all)、limit(0/1/20000/20001)、start_time+end_time、range_seconds。",
     "过滤正确；limit 越界被夹取到 1–20000；无 500。"),
    ("TC-API-MON-03", "7 API 系统测试", "retention 越界", "P1",
     "",
     "POST retention_days = 0 / 8 / -1 / 3.5 / \"abc\"。",
     "拒绝，仅接受 1–7 整数。"),
    ("TC-API-MON-04", "7 API 系统测试", "weights_top 非法", "P1",
     "",
     "POST 负权重 / 非整。",
     "拒绝（非负约束）。"),
    ("TC-API-MON-05", "7 API 系统测试", "乐观并发冲突（重点）", "P1",
     "GET 取得 updated_at。",
     "1. 客户端 A 用旧 expected_updated_at POST retention/weights_top/passive_control。\n2. 之前先由客户端 B 成功改一次（使 updated_at 变化）。",
     "A 收到 409 CONFLICT，data.current 返回服务端当前值。"),
    ("TC-API-CT-01", "7 API 系统测试", "畸形请求健壮性", "P1",
     "",
     "对全部 POST 端点发送畸形 JSON、错误 Content-Type、超大 body。",
     "稳定返回错误码，不 500 崩溃、不泄露堆栈。"),
    ("TC-API-CT-02", "7 API 系统测试", "错误 HTTP 方法", "P1",
     "",
     "对 GET-only 端点用 POST，反之亦然。",
     "405 或规范错误返回。"),

    # ===== 8 配置项覆盖 P1 =====
    ("TC-CFG-THR-01", "8 配置-阈值与权重", "thresholds 分级边界", "P1",
     "配置：thresholds(low/medium/high/critical)。生效：经 update_config_section 可热更新；手改需重启。",
     "把 high 从 0.8 改小（如 0.5）→（重启或热更）→ 施加中等压力 → 看 dynamic_info.pressure.level。",
     "更低压力即被判为 high；分级边界随配置移动。"),
    ("TC-CFG-WT-01", "8 配置-阈值与权重", "weights（压力合成权重 cpu2/mem7/io1）", "P1",
     "配置：weights。生效：改后重启。",
     "把 memory 权重调低、cpu 调高，重启；分别单独施加内存压力与 CPU 压力，比较合成 score 变化。",
     "合成压力分数对 CPU 更敏感、对内存更不敏感。"),
    ("TC-CFG-WTOP-01", "8 配置-阈值与权重", "weights_top（排名 cpu2/mem7/gpu5）", "P1",
     "配置：weights_top。生效：/monitor/config/weights_top 热更新回写。",
     "POST 提高 gpu 权重 → 立即看 App Resources 榜 → cat config.yaml 看 weights_top.gpu。",
     "GPU 重的 app 排名上升；YAML 已回写；I/O 榜不受影响（纯吞吐）。"),
    ("TC-CFG-LP-01", "8 配置-限额策略", "CPU rate 比例", "P1",
     "配置：limit_policy.cpu.rate.{high,medium,low,undefined}。生效：可经 update_limit_policy_for_priority 回写；手改需重启。",
     "把 low 从 0.4 改为 0.2 →（重启/热更）→ 对 low 优先级 app 下发限额 → cat cpu.max。",
     "cpu.max 配额按新比例 0.2 换算。"),
    ("TC-CFG-LP-02", "8 配置-限额策略", "memory rate 比例", "P1",
     "",
     "同上改 limit_policy.memory.rate.high → 验证 memory.high 值随之变化。",
     "一致。"),
    ("TC-CFG-LP-03", "8 配置-限额策略", "disk_io rate（read/write/iops）", "P1",
     "",
     "改 limit_policy.disk_io.rate.low.write（如 20→10）→ 重启 → 下发 low 限额 → cat io.max + fio 实测。",
     "io.max wbps 与实测写吞吐随新值变化。"),
    ("TC-CFG-LP-04", "8 配置-限额策略", "policy 模式 combined vs separated", "P1",
     "配置：limit_policy.policy。生效：重启。",
     "切换 combined / separated，分别只施加 CPU 压力或只施加磁盘压力，观察是否联动限额。",
     "combined 下 cpu/mem/disk 同条件联动；separated 下各自独立评估。"),
    ("TC-CFG-LP-05", "8 配置-限额策略", "资源开关 enabled", "P1",
     "",
     "把 limit_policy.cpu.enabled 设为 false，重启，触发限额。",
     "CPU 不被限，其它资源仍按配置限。"),
    ("TC-CFG-DAF-01", "8 配置-限额策略", "dominant_app_reduce_factor", "P1",
     "配置：dominant_app_reduce_factor（默认 3.5）。生效：重启。",
     "构造\"被限主导 app 且系统不忙\"场景，改因子值前后对比权重/调整力度。",
     "权重与调整因子按该值缩减，行为符合策略。"),
    ("TC-CFG-BUSY-01", "8 配置-忙碌阈值", "cpu/memory/disk busy 阈值", "P1",
     "配置：cpu_busy_threshold、memory_busy_threshold、disk_utilization_threshold、disk_iowait_threshold、disk_io_throughput_threshold_kb。生效：重启。",
     "逐项调低阈值 → 重启 → 施加低于原阈值的负载 → 观察是否更早判\"忙\"并触发相应控制。",
     "忙碌判定点随阈值移动。"),
    ("TC-CFG-PRIO-01", "8 配置-优先级映射", "优先级数值映射", "P1",
     "配置：app_priority(critical100/high80/medium50/low20)。生效：重启。",
     "修改某级数值 → 重启 → 查询 get_pending_app 的 priority_value 与队列排序。",
     "队列排序与数值映射一致。"),
    ("TC-CFG-NET-01", "8 配置-网络控制", "enable_network_control 开关", "P1",
     "",
     "设 false → 重启 → tc qdisc show。",
     "不下发任何 tc/iptables 网络规则。"),
    ("TC-CFG-NET-02", "8 配置-网络控制", "network_interface", "P1",
     "",
     "改为真实的另一网卡 → 重启 → 检查规则挂载的接口。",
     "规则挂在新接口上。（不存在的接口见 TC-SF-07）"),
    ("TC-CFG-NET-03", "8 配置-网络控制", "network_bandwidth_kbit 总带宽", "P1",
     "",
     "调整总带宽 → 重启 → iperf3 实测上限。",
     "总带宽上限随配置变化。"),
    ("TC-CFG-NET-04", "8 配置-网络控制", "config_network_bw 各优先级区间", "P1",
     "",
     "修改 high.max → 重启 → 对 high 类 app 打流。",
     "该优先级带宽上限随之变化。"),
    ("TC-CFG-NET-05", "8 配置-网络控制", "network_thresholds", "P1",
     "",
     "调低 critical 阈值 → 重启 → 打流。",
     "更低网络压力即触发带宽收紧。"),
    ("TC-CFG-NET-06", "8 配置-网络控制", "network_system_ports 豁免", "P1",
     "",
     "向列表新增一个端口（如 8080）→ 重启 → 该端口打流。",
     "新增端口流量被豁免不限速。"),
    ("TC-CFG-NET-07", "8 配置-网络控制", "network_burst_map", "P1",
     "",
     "修改各优先级 burst 值 → 重启 → 检查 tc class 的 burst。",
     "burst 随配置变化。"),
    ("TC-CFG-BL-01", "8 配置-黑名单", "新增黑名单项", "P1",
     "",
     "向 blacklist 增加一个测试进程名 → 重启 → 该进程运行时执行 discover_search 与 top 采样。",
     "该进程从向导候选与监控采样中被隐藏，且不被纳管/限制。"),
    ("TC-CFG-TIME-01", "8 配置-时间/间隔", "cooldown_time", "P1",
     "",
     "改 cooldown_time（如 15→60）→ 重启 → 在压力临界波动。",
     "限额调整最小间隔随之变化（对照 TC-CT-LOOP-02）。"),
    ("TC-CFG-TIME-02", "8 配置-时间/间隔", "采集/空闲检查间隔", "P1",
     "配置：regular_update_sys_pressure_time、monitor_idle_check_interval。生效：重启。",
     "调整后重启，观察压力刷新频率 / 空闲检查频率。",
     "频率随配置变化。"),
    ("TC-CFG-PASV-01", "8 配置-被动控制", "passive_resource_control 热更新", "P1",
     "",
     "见 TC-FN-BL-07：/monitor/config/passive_control 热更新回写并即时生效。",
     "热更新回写并即时生效。"),
    ("TC-CFG-APP-01", "8 配置-受控应用", "controlled_apps 五字段解析", "P1",
     "",
     "手动在 controlled_apps 加一条含 name/id/commandline/bpf_name/process_names 的条目 → 重启 → 启动匹配进程。",
     "balancer 按各字段识别、监控、聚合、显示名正确。（向导路径见 TC-FN-BL-02）"),
    ("TC-CFG-ROB-01", "8 配置-健壮性", "非法/缺失配置", "P1",
     "",
     "制造非法 YAML（类型错误、缺关键 section、越界值、语法错误）→ 启动服务。",
     "启动时校验并明确报错拒绝，或安全回退默认值，不带坏值静默运行。"),
    ("TC-CFG-ROB-02", "8 配置-健壮性", "回写不破坏文件", "P1",
     "",
     "多次经 API 热更新（weights_top/limit_policy）后 cat config.yaml。",
     "仅目标行被改，注释与缩进/其它内容保持不变（config.py 的 patcher 声称保留注释）。"),

    # ===== 9 安全测试 P1 =====
    ("TC-SEC-01", "9 安全测试", "命令注入（重点）", "P1",
     "后端调用 cpupower/iptables/tc/pgrep 传入用户可控字段。",
     "向 discover_search.keywords、new_controlled_app 的 name/id/commandline/bpf_name/process_names 注入 shell 元字符：; | & $() 反引号 换行 空格 --flag；提交后观察系统与日志。",
     "参数被安全转义/参数化，不执行注入命令，无非预期文件/进程/规则产生。"),
    ("TC-SEC-02", "9 安全测试", "路径穿越", "P1",
     "",
     "commandline/cgroup 传 ../../ 或指向敏感 cgroup 路径。",
     "校验/限定作用域，不操作非预期 cgroup。"),
    ("TC-SEC-03", "9 安全测试", "pid 越权", "P1",
     "",
     "discover_extract.pids 传系统关键进程/非本 app pid。",
     "不越权读取/操作。"),
    ("TC-SEC-04", "9 安全测试", "鉴权与弱哈希", "P1",
     "",
     "审查 token 校验（SHA256 是否加盐）、会话管理、暴力尝试是否限速。",
     "记录风险；无绕过；建议加盐/限速。"),
    ("TC-SEC-06", "9 安全测试", "CORS * + CSRF", "P1",
     "",
     "从跨站页面向控制端点发请求（CORS 为 *）。",
     "评估本地服务开放 * 的风险，验证是否需同源/自定义 Token 头防护。"),
    ("TC-SEC-07", "9 安全测试", "TLS 配置", "P1",
     "",
     "sslscan/nmap --script ssl-enum-ciphers -p 9001 localhost。",
     "现代 TLS，无弱套件。"),
    ("TC-SEC-08", "9 安全测试", "信息泄露", "P1",
     "",
     "触发各类错误，检查响应/日志。",
     "不含堆栈、绝对路径、token 等敏感信息。"),
    ("TC-SEC-09", "9 安全测试", "资源耗尽", "P1",
     "",
     "海量并发 SSE 连接 / 超大 keywords / 高频请求。",
     "有上限或限速，不被单点打挂。"),
    ("TC-SEC-10", "9 安全测试", "静态与依赖扫描", "P1",
     "",
     "运行 coverity（已存在 coverity_build/）与 trivy 依赖扫描。",
     "高危项清零。"),

    # ===== 10 兼容性/降级 P1 =====
    ("TC-CP-01", "10 兼容性/降级", "MTL/PTL/WideCat Lake", "P1",
     "", "三平台各跑一轮功能+调控冒烟。", "采集与控制均正常。"),
    ("TC-CP-02", "10 兼容性/降级", "无 NPU", "P1",
     "", "查看 NPU 卡片与 static_info。", "标\"不支持\"，非误显 0%。"),
    ("TC-CP-03", "10 兼容性/降级", "无 iGPU", "P1",
     "", "同上查 GPU。", "同上（标\"不支持\"，非误显 0%）。"),
    ("TC-CP-04", "10 兼容性/降级", "内核未启用 PSI", "P1",
     "", "缺 /proc/pressure/* 时启动。", "压力功能优雅降级 + 提示。"),
    ("TC-CP-05", "10 兼容性/降级", "cgroups v1/无 v2", "P1",
     "", "在 v1 环境启动。", "控制功能安全禁用 + 提示。"),
    ("TC-CP-06", "10 兼容性/降级", "无 BCC", "P1",
     "", "卸载 bcc 后启动。", "eBPF 降级/禁用，不崩溃。"),
    ("TC-CP-07", "10 兼容性/降级", "无 cpupower", "P1",
     "", "卸载后触发 governor。", "功能禁用 + 告警。"),
    ("TC-CP-08", "10 兼容性/降级", "多盘/多网卡", "P1",
     "", "检查按设备区分。", "采集与限额按设备正确区分。"),
    ("TC-CP-09", "10 兼容性/降级", "浏览器", "P1",
     "", "Chrome/Edge/Firefox。", "UI 与 SSE 均正常。"),

    # ===== 11 性能 P2 =====
    ("TC-PF-UI-01", "11 性能", "页签切换流畅度", "P2",
     "",
     "用 DevTools Performance 录制在 6 个页签间切换。",
     "切换 < 300ms，无明显卡顿/长任务。"),
    ("TC-PF-UI-02", "11 性能", "大进程列表渲染", "P2",
     "进程数 > 1000。",
     "打开 Processes，测首屏与滚动帧率。",
     "首屏 < 1s，滚动流畅。"),
    ("TC-PF-BE-01", "11 性能", "接口时延", "P2",
     "",
     "对监控端点做压测（如 ab/wrk/hey），统计 P50/P95。",
     "在约定阈值内。"),
    ("TC-PF-BE-02", "11 性能", "SmarTune 自身开销（关键）", "P2",
     "",
     "空闲态与\"千级进程负载\"下，用 top -p <backend_pids> / pidstat 观察后端 CPU/内存占用，持续 30 min。",
     "自身占用低而稳定（降压工具不能反成负担）；无持续增长。"),
    ("TC-PF-BE-04", "11 性能", "多客户端负载", "P2",
     "",
     "并发 N 个浏览器/脚本（SSE + 2s 轮询）。",
     "后端负载平稳，响应不劣化。"),

    # ===== 12 稳定性 P2 =====
    ("TC-ST-01", "12 稳定性/长稳", "多 UI 并发改同一配置", "P2",
     "",
     "多个浏览器同时改 weights_top/retention/passive（携带各自 expected_updated_at）。",
     "乐观并发正确，落败方得 409，最终一致，无脏写。"),
    ("TC-ST-02", "12 稳定性/长稳", "多 UI 并发限额同一 app", "P2",
     "",
     "多客户端并发对同一 app limit/restore。",
     "无竞态导致的错误 cgroup 状态。"),
    ("TC-ST-03", "12 稳定性/长稳", "反复切换/开关（数小时）", "P2",
     "",
     "脚本驱动反复切页签、开关 Refresh，持续数小时；监控前端内存与后端连接数。",
     "无内存增长、无 SSE 连接泄漏。"),
    ("TC-ST-04", "12 稳定性/长稳", "长稳压力起伏（24–72h）", "P2",
     "",
     "长时间周期性施压/撤压，持续跑闭环。",
     "闭环持续正确，无泄漏、无残留累积。"),
    ("TC-ST-06", "12 稳定性/长稳", "高频 app 启停", "P2",
     "",
     "脚本高频启动/退出受控 app（触发大量 execve/exit）。",
     "eBPF 事件不丢/不乱序导致状态错乱。"),

    # ===== 13 持久化 P2 =====
    ("TC-PS-01", "13 持久化", "保留期清理", "P2",
     "",
     "设 retention=1 天，注入超期快照（或调时钟）→ 触发清理 → 查 DB 行数与返回 deleted。",
     "过期快照被真实删除，数据量受控。"),
    ("TC-PS-02", "13 持久化", "DB 体积有界", "P2",
     "",
     "长时间持续写快照，监控 SQLite 文件大小。",
     "随保留期收敛，不无限增长。"),
    ("TC-PS-03", "13 持久化", "DB 损坏恢复", "P2",
     "",
     "模拟 DB 文件损坏/被占用后启动。",
     "优雅处理，不崩溃，有明确日志。"),
    ("TC-PS-04", "13 持久化", "config+DB+BPF 三方一致性", "P2",
     "",
     "执行 new / remove / purge 后，分别核对 config.yaml、DB 记录、BPF 匹配缓存。",
     "三处一致，无孤儿记录。"),
    ("TC-PS-05", "13 持久化", "升级迁移", "P2",
     "",
     "用旧版本 DB/config 升级到新版本启动。",
     "schema/config 兼容迁移，旧数据可用。"),

    # ===== 14 单元测试 =====
    ("UT-01", "14 单元测试", "配额计算", "保留",
     "", "优先级比例 × 上下界 → cpu.max/memory.high/io.max；含边界(0、超界、undefined)。",
     "配额计算正确，边界值处理正确。"),
    ("UT-02", "14 单元测试", "压力分数与四级分级", "保留",
     "", "weights + thresholds 边界值。", "分级正确。"),
    ("UT-03", "14 单元测试", "排名 score", "保留",
     "", "weights_top 加权；I/O 纯吞吐。", "排序与分值正确。"),
    ("UT-04", "14 单元测试", "优先级队列排序/取消", "保留",
     "", "DESC 稳定序。", "排序稳定、取消正确。"),
    ("UT-05", "14 单元测试", "配置解析与校验", "保留",
     "", "缺字段/非法值/类型错误被拒（config.py from_file / update_* / patcher）。",
     "非法配置被拒绝。"),
    ("UT-06", "14 单元测试", "YAML patcher 保注释", "保留",
     "", "update_config_section / append_to_list_section / remove_from_list_section 不破坏注释与缩进。",
     "注释与缩进保持不变。"),
    ("UT-07", "14 单元测试", "网络带宽区间/端口豁免映射", "保留",
     "", "各优先级 min/max、system_ports。", "映射正确。"),
]

HEADERS = ["用例编号", "所属模块/章节", "用例名称", "优先级", "前置条件", "测试步骤", "预期结果",
           "实际结果", "状态", "备注"]

wb = Workbook()
ws = wb.active
ws.title = "测试用例"

# 样式
header_fill = PatternFill("solid", fgColor="4472C4")
header_font = Font(bold=True, color="FFFFFF", size=11)
thin = Side(style="thin", color="BFBFBF")
border = Border(left=thin, right=thin, top=thin, bottom=thin)
wrap_top = Alignment(wrap_text=True, vertical="top")
center = Alignment(horizontal="center", vertical="center", wrap_text=True)

prio_fill = {
    "P0": PatternFill("solid", fgColor="FFC7CE"),
    "P1": PatternFill("solid", fgColor="FFEB9C"),
    "P2": PatternFill("solid", fgColor="C6EFCE"),
    "保留": PatternFill("solid", fgColor="D9D9D9"),
}

# 表头
ws.append(HEADERS)
for col, _ in enumerate(HEADERS, start=1):
    c = ws.cell(row=1, column=col)
    c.fill = header_fill
    c.font = header_font
    c.alignment = center
    c.border = border

# 数据
for r, row in enumerate(ROWS, start=2):
    values = list(row) + ["", "", ""]  # 实际结果/状态/备注 留空
    for col, val in enumerate(values, start=1):
        c = ws.cell(row=r, column=col, value=val)
        c.border = border
        if col in (1, 4, 9):  # 编号/优先级/状态居中
            c.alignment = center
        else:
            c.alignment = wrap_top
    # 优先级底色
    pc = ws.cell(row=r, column=4)
    if pc.value in prio_fill:
        pc.fill = prio_fill[pc.value]
        pc.font = Font(bold=True)

# 列宽
widths = [18, 22, 26, 8, 34, 52, 52, 20, 10, 16]
for i, w in enumerate(widths, start=1):
    ws.column_dimensions[get_column_letter(i)].width = w

# 冻结表头 + 自动筛选
ws.freeze_panes = "A2"
ws.auto_filter.ref = f"A1:{get_column_letter(len(HEADERS))}{len(ROWS)+1}"

out = "/home/raspadmin/xiaojing/code/develop/intel-xpu-smartune-main/docs/TEST_PLAN.xlsx"
wb.save(out)
print(f"saved: {out}")
print(f"total cases: {len(ROWS)}")
